export const USER_SIGNUP_REQ = "USER_SIGNUP_REQ";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL";

export const FETCH_BOOKS_REQ = "FETCH_BOOKS_REQ";
export const FETCH_BOOKS_SUCCESS = "FETCH_BOOKS_SUCCESS";
export const FETCH_BOOKS_FAIL = "FETCH_BOOKS_FAIL";

export const SET_ORDER_REQ = "SET_ORDER_REQ";
export const SET_ORDER_SUCCESS = "SET_ORDER_SUCCESS";
export const SET_ORDER_FAIL = "SET_ORDER_FAIL";
export const SET_ORDER_RESET = "SET_ORDER_RESET";

export const GET_LAST_REQ = "GET_LAST_REQ";
export const GET_LAST_SUCCESS = "GET_LAST_SUCCESS";
export const GET_LAST_FAIL = "GET_LAST_FAIL";

export const USER_SIGNIN_REQ = "USER_SIGNIN_REQ";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";

export const FETCH_USED_BOOKS_SUCCESS = "FETCH_USED_BOOKS_SUCCESS";
export const FETCH_USED_BOOKS_FAIL = "FETCH_USED_BOOKS_FAIL";
