const arabicTranslate = {
  headerSignup: "اشتراك",
  copyright: "Copyright for Code land-2021",
  footerDescription:
    "مشروع كتبي هو مشروع يمكنك الاستفادة منه كأكبر مصدر كردي حيث يمكنك طلب الكتب من كل المكتبات المشاركة في هذا المشروعيمكننا توصيل الكتب إليك مجانا ، وسنتحمل نحن المسؤولية عنها. يمكنك استبدال كتبك مع شخص آخر أو عرضها للبيع للسماح للأشخاص الاخرين بالاستفادة منها.",
  username: "اسم المستخدم",
  phoneNumber: "رقم الهاتف",
  headerSignin: "تسجيل الدخول",
  headerLanguages: "اللغات",
  headerHome: "الصفحة الرئيسية",
  headerBooks: "الكتب",
  headerSearch: "بحث",
  headerUsedbooks: "الكتب المستعملة",
  headerContactus: "اتصل بنا",
  headerAbout: "حول",
  latestBooks: "احدث الكتب",
  whatcanYoudo: "ما يمكنك ان تفعل؟",
  exchangeTitle: "تبادل",
  exchangeDescription:
    "يمكنك رؤية الكتب التي أضافها شخص اخر لاستبدالها بكتب اخرى. او يمكنك إضافة الكتب الخاصة بك إلى هنا لاستبدالها",
  sellTitle: "بيع",
  sellDescription:
    "يمكنك رؤية الكتب التي يريد شخص اخر بيعها ، ويمكنك شراء أي كتب تريدها. او يمكنك إضافة الكتب الخاصة بك لبيعها",
  booksTitle: "الكتب",
  booksDescription:
    "يمكنك رؤية جميع الكتب التي أضافتها المكتبات ، ويمكنك شراء الكتب الجديدة بقدر ما تريد.",
  emailAdress: "بريد الالكتروني",
  password: "كلمة السر",
  confirmPassword: "تاكيد كلمة السر",
  submitButton: "ارسال",
  allBooks: "جميع الكتب",
  headerMyorders: "طلباتي",
  headerOrders: "طلبات",
  idList: "هوية",
  bookName: "اسم الكتاب",
  quantity: "العدد",
  bookstore: "المكتبة",
  price: "السعر",
  date: "التاريخ",
  profileHeader: "الملف الشخصي",
  name: "الاسم",
  clicktoChangepassword: "انقر لتغير كلمة السر",
  updatePassword: "تحديث كلمة السر",
  currentPassword: "كلمة السر الحالية",
  newPassword: "كلمة السر الجديدة",
  changeSection: "تغيير",
  headerBeseller: "كن بائعا",
  headersellYourbook: "بيع كتابك",
  categorySection: "الفئة",
  categoryBranches: "اختيار الفئة",
  novelCategory: "رواية",
  epicCategory: "ملحمة",
  poemCategory: "شعر",
  language: "اللغة",
  adress: "العنوان",
  parts: "اجزاء",
  image: "صور",
  imageChoosefile: "اختيار ملف",
  imageNofile: "لم يتم اختيار اي ملف",
  description: "تفاصيل",
  whatdoYouwant: "ماذا تريد؟",
  sellmybookChoice: "بيع كتابي",
  exchangemybookChoice: "تبادل كتابي",
  author: "الكاتب",
  usedBooks: "كتب مستعملة",
  usedbooksNew: "جديد",
  usedbooksUsed: "مستعمل",
  subject: "موضوع",
  message: "رسالة",
  kaleMuhammad: "Kale Muhammad",
  founder: "مؤسس",
  founderDescription: "مؤسس المشروع",
  rawandRebwar: "Rawand Rebwar",
  developer: "مطور",
  developerDescription: "مالك و مطور المشروع",
  contactButton: "اتصال",
  headermyBasket: "سلتي",
  headerLogout: "تسجيل الخروج",
  addtoMybasket: "الاضافة الى سلتي",
  deleteButton: "مسح",
  totalPrice: "مجموع السعر",
  iqdTerm: "دينار عراقي",
  myAdress: "عنواني",
  streetAddress: "عنوان الشارع",
  fullAdress: "العنوان الكامل",
  note: "ملاحظة",
  getLocation: "احصل على العنوان",
  call: " اتصال",
  relatedBooks: "کـتـێـبـی پـەیـوەنـدیدار",
  dashboard: "داشبورد",
};

export default arabicTranslate;
