const englishTranslate = {
  headerSignup: "Sign up",
  copyright: "Copyright for Code land-2021",
  footerDescription: "'my books' project is a project that you can get benefits from it as the biggest Kurdish source that you can order a book from any Libraries that have participated in this project. It is free to deliver the books to you, and we will take responsibility for them. You can exchange your books for someone else or put them for sale to let people get benefits from them.",
  username: "username",
  phoneNumber: "Phone number",
  headerSignin: "Sign in",
  headerLanguages: "Languages",
  headerHome: "Home",
  headerBooks: "Books",
  headerSearch: "Search",
  headerUsedbooks: "Used books",
  headerContactus: "Contact us",
  headerAbout: "About",
  latestBooks: "Latest books",
  whatcanYoudo: "What can you do?",
  exchangeTitle: "Exchange",
  exchangeDescription: "You can see the books that someone added to exchange them for another book. Also you can add yours to here",
  sellDescription: "You see the books that someone wants to sell, and you can buy any books you want. Also you can add yours to here the used books.",
sellTitle : "Sell",
booksTitle: "See All Books",
  booksDescription: "You can see all the books that the Bookstores added, and you can buy the new books as much as you want",
  emailAdress: "Email adress",
  password: "Password",
  confirmPassword: "Confirm password",
  submitButton: "Submit",
  allBooks: "All books",
  headerMyorders: "My orders",
  headerOrders: "Orders",
  idList: "ID",
  bookName: "Book name",
  quantity: "Quantity",
  bookstore: "Bookstore",
  price: "Price",
  date: "Date",
  profileHeader: "Profile",
  name: "Name",
  clicktoChangepassword: "Click to change password",
  updatePassword: "Update password",
  currentPassword: "Current password",
  newPassword: "New password",
  changeSection: "Change",
  headerBeseller: "Be seller",
  headersellYourbook: "Sell your book",
  categorySection: "Category",
  categoryBranches: "choose category",
  novelCategory: "Novel",
  epicCategory: "Epic",
  poemCategory: "Poem",
  language: "Language",
  adress: "Adress",
  parts: "Parts",
  image: "Image",
  imageChoosefile: "Choose file",
  imageNofile: "No file chosen",
  description: "Description",
  whatdoYouwant: "What do you want?",
  sellmybookChoice: "Sell my book",
  exchangemybookChoice:"Exchange my book",
  author: "Author",
  usedBooks: "Used books",
  usedbooksNew: "New",
  usedbooksUsed: "Used",
  subject: "Subject",
  message: "Message",
  kaleMuhammad: "Kale Muhammad",
  founder: "Founder",
  founderDescription: "Founder of the project",
  rawandRebwar: "Rawand Rebwar",
  developer: "Developer",
  developerDescription: "Owner and developer of the project",
  contactButton: "Contact",
  headermyBasket: "My basket",
  headerLogout: "Logout",
  addtoMybasket: "Add to my basket",
  deleteButton: "Delete",
  totalPrice: "Total price",
  iqdTerm: "IQD",
  myAdress: "My adress",
  streetAddress : "Street Address",
  fullAdress: "Full adress",
  note: "Note",
  getLocation: "Get location",
  call: "Call",
  relatedBooks: "Related Books",
  dashboard: "Dashboard",

};

export default englishTranslate;