const kurdishTranslate = {
  headerSignup: "خۆ تۆمارکردن",
  copyright: "مافی پارێزراوە بۆ کۆدلاند-2021",
  footerDescription: " پڕۆژەی 'کتێبەکانم' پڕۆژەیەکە کە دەتوانیت سوودی لێ ببینیت وەک گەورەترین سەرچاوەی کوردی کە دەتوانیت کتێب داوا بکەیت لە هەر کتێبخانەیەک کە بەشداری کردووە لەم پڕۆژەیەدا. گەیاندنی کتێبەکان بە خوێنەر بەخۆڕاییە و ئێمە بەرپرسیارێتی هەڵدەگرین. دەتوانیت کتێبەکەت لەگەڵ کەسێکی تردا بگۆڕیتەوە، یاخود دایان بنێیت بۆ فرۆشتن تاوەکو خەڵک سودی لێ ببینێت",
  username: "ناوی بەکارهێنەر",
  phoneNumber: "ژمارەی مۆبایل",
  headerSignin: "چوونە ژوورەوە",
  headerLanguages: "زمانەکان",
  headerHome: "پەڕەی سەرەکی",
  headerBooks: "کتێبەکان",
  headerSearch: "گەڕان",
  headerUsedbooks: "کتێبە بەکارهاتووەکان",
  headerContactus: "پەیوەندی بکە",
  headerAbout: "دەربارە",
  latestBooks: "دوایین کتێبەکان",
  whatcanYoudo: "دەتوانیت چی بکەیت؟",
  exchangeTitle: "گۆڕینەوە",
  exchangeDescription: "لێرەدا دەتوانیت ئەو کتێبانە ببینیت کە کە کەسێک زیادی کردووە بۆ ئەوەی بیانگۆڕێتەوە بە کتێبی تر. بەهەمان شێوە دەتوانیت ئەوانەی خۆت بۆ ئێرە زیاد بکەیت",
  sellTitle: "فرۆشتن",
  sellDescription: "لێرەدا ئەو کتێبانە دەبینیت کە کەسێک دەیەوێت بیفرۆشێت، هەروەها دەتوانیت هەر کتێبێک بکڕیت کە دەتەوێت. بەهەمان شێوە دەتوانیت کتێبەکانی خۆت بۆ بەشی فرۆشتن زیاد بکەیت ",
  booksTitle: "کتێبەکان",
  booksDescription: "لێرەدا دەتوانیت هەموو ئەو کتێبانە ببینیت کە کتێبخانەکان زیادی دەکەن، هەروەها دەتوانیت چەند دەتەوێت کتێب بکڕیت",
  emailAdress: "ئیمەیڵ",
  password: "وشەی نهێنی",
  confirmPassword: "دوپاتکردنەوەی وشەی نهێنی",
  submitButton: "ناردن",
  allBooks: "کتێبەکان",
  headerMyorders: "داواکارییەکانم",
  headerOrders: "داواکارییەکان",
  idList: "پێناس",
  bookName: "ناوی کتێب",
  quantity: "ڕێژە",
  bookstore: "کتێبخانە",
  price: "نرخ",
  date: "بەروار",
  profileHeader: "پڕۆفایل",
  name: "ناو",
  clicktoChangepassword: "کلیک بکە بۆ گۆڕینی وشەی نهێنی",
  updatePassword: "تازەکردنەوەی وشەی نهێنی",
  currentPassword: "وشەی نهێنی ئێستا",
  newPassword: "وشەی نهێنی نوێ",
  changeSection: "گۆڕین",
  headerBeseller: "فرۆشتن",
  headersellYourbook: "کتێبەکەت بفرۆشە",
  categorySection: "جۆر",
  categoryBranches: "جۆر هەڵبژێرە",
  novelCategory: "ڕۆمان",
  epicCategory: "داستان",
  poemCategory: "هۆنراوە",
  language: "زمان",
  adress: "ناونیشان",
  parts: "بەش",
  image: "وێنە",
  imageChoosefile: "فایلێک هەڵبژێرە",
  imageNofile: "هیچ فایلێکی هەڵبژێردراو نییە",
  description: "باسکردن",
  whatdoYouwant: "چیت دەوێت؟",
  sellmybookChoice: "کتێبەکەم بفرۆشم",
  exchangemybookChoice:"کتێبەکەم بگۆڕمەوە",
  author: "نووسەر",
  usedBooks: "کتێبە بەکارهاتووەکان",
  usedbooksNew: "نوێ",
  usedbooksUsed: "بەکارهاتوو",
  subject: "بابەت",
  message: "پەیام",
  kaleMuhammad: "کاڵێ محمد",
  founder: "دامەزرێنەر",
  founderDescription: "دامەزرێنەری پڕۆژە",
  rawandRebwar: "ڕەوەند ڕێبوار",
  developer: "گەشەپێدەر",
  developerDescription: "گەشەپێدەر و خاوەنی پڕۆژە",
  contactButton: "پەیوەندی کردن",
  headermyBasket: "سەبەتەکەم",
  headerLogout: "دەرچوون",
  addtoMybasket: "زیادکردن بۆ سەبەتەکەم",
  deleteButton: "سڕینەوە",
  totalPrice: "نرخی گشتی",
  iqdTerm: "دیناری عێراقی",
  myAdress: "ناونیشانم",
  streetAddress : "ناونیشانی شەقام",
  fullAdress: "ناونیشانی تەواو",
  note: "تێبینی",
  getLocation: "ناونیشان وەربگرە",
  call: "پەیوەندی بکە",
  relatedBooks: "کـتـێـبـی پـەیـوەنـدیدار",
  dashboard: "داشبۆڕد",

};

export default kurdishTranslate;